#:schema node_modules/wrangler/config-schema.json
name = "email-to-json-worker"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "email-to-json"
preview_bucket_name = "email-to-json-preview"
